# Generated by Django 5.2.13 on 2026-04-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='actual_duration',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Durée réelle en minutes', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix à la minute (video) ou prix total (fixed)', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('video', 'Visio (à la minute)'), ('fixed', 'Service Fixe')], default='video', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_min',
            field=models.PositiveSmallIntegerField(default=60, help_text='Durée estimée'),
        ),
    ]
