# Generated by Django 5.2.13 on 2026-04-27 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_service_price_booking_actual_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration_requested',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Durée max demandée en minutes', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.service'),
        ),
    ]
