# Generated by Django 5.2.13 on 2026-04-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_duration_requested_booking_slot_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('waiting_expert', 'Attente expert'), ('accepted', 'Acceptée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
