# Generated by Django 5.2.13 on 2026-04-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
