# Generated by Django 5.2.13 on 2026-04-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_expertrequest_bio_expertrequest_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertrequest',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='expertrequest',
            name='title',
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
