# Generated by Django 5.2.13 on 2026-04-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_remove_expertrequest_bio_remove_expertrequest_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
