# Generated by Django 5.2.13 on 2026-04-09 01:45

import django.db.models.deletion
import video_sessions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_remove_service_price_booking_actual_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_link', models.URLField(default=video_sessions.models.generate_jitsi_link, max_length=500)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_session', to='bookings.booking')),
            ],
        ),
    ]
